### PR TITLE
Allow overriding the name of layouts. Similar to the alias PR.

### PR DESCRIPTION
**Pull request by tlsomers**
@Janthor This is how I would do it, just allow setting the name field

### CODE REVIEW

**Comment by Janthor** [comment]
I thought there was a reason for the name variable being static(referencing it from other places maybe), if it wouldn't hurt to change it it'd probably be the best solution.

**Comment by tlsomers** [comment]
It's only used in LayoutName which is a property so changes automatically, and LayoutName is only used for the bar item, so it shouldn't cause any harm

**Review by Janthor — COMMENTED** [review]
I dunno how much my review is worth, but I tried it locally and it's failing to run when I try to set the name from the config.
```
Microsoft.CodeAnalysis.Scripting.CompilationErrorException: '(143,13): error CS0200: Property or indexer "DwindleLayoutEngine.Name" cannot be assigned to -- it is read only'
```
I honestly think something is wrong with visual studio and it's not properly compiling the changes for some reason, but I also can't get it to compile correctly even after cleaning and rebuilding the solution multiple times

This is how I was declaring the name in the config:
```csx
    Func<ILayoutEngine[]> defaultLayouts = () => new ILayoutEngine[]
    {
        new DwindleLayoutEngine(1,0.7,0.03){
            Name = "侀"
        },
    }
```

**Comment by tlsomers** [comment]
@Janthor remember to rebuild the entire solution, and make sure that your r directives point to the build output. It's just an outdated dll

**Comment by Janthor** [comment]
> @Janthor remember to rebuild the entire solution, and make sure that your r directives point to the build output. It's just an outdated dll

Oooooh forgot to change out the DLLs in the config, sorry lmao

**Review by Janthor — APPROVED** [review]
Confirmed working 
image

**Review by josteink — APPROVED** [review]
LGTM

**Pull request merged**
