### PR TITLE
Add config docs to help VSCode pick correct .NET

### PR DESCRIPTION
**Pull request by alexnguyennn**
Hi there, 

I ran into #109 a while ago and eventually found a way to resolve it locally.
Thought I'd upstream some documentation to help others get intellisense/typechecking back in their configs if they've run into this too.

Happy to make any further changes required.
Thanks!

### CODE REVIEW

**Review by dalyIsaac — APPROVED** [review]
LGTM!

This is great fix.

**Comment by alexnguyennn** [comment]
thanks for the review @dalyIsaac. 
Just noticed some typos/formatting issues; I'll squash it in to keep the log clean but may need another approve if they reset😅

**Comment by dalyIsaac** [comment]
@alexnguyennn is it alright with you if I push some formatting changes to make [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) happy? Alternatively, you could do them yourself.

**Comment by alexnguyennn** [comment]
all good, I've gone and made the changes myself and squashed them in too - `markdownlint` extension is happy on my local at least with the default settings now :)

**Comment by josteink** [comment]
Wow. That’s nice research and good documentation. Approved 🙂

**Review by josteink — APPROVED** [review]

**Pull request merged**
