### PR TITLE
Added gaps plugin.

### PR DESCRIPTION
**Pull request by dalyIsaac**
This PR adds the ability to customize the gap between windows. This takes the form of the **"outer"** gap, and the **"inner"** gap.

image
image

This PR tries to account for @rickbutton's comment in https://github.com/rickbutton/workspacer/pull/161#issuecomment-749920696 by implementing a plugin using `IConfigContext::AddLayoutProxy`. 

Currently, the gap size is global - i.e., changing the gap in one workspace changes the gap in all workspaces. A local option can probably be added in the future, if so desired.

I've also added a sample snippet to `snippets/gaps.cs`.

Related issues: #161 #95

### CODE REVIEW

**Review by josteink — APPROVED** [review]
Haven't tested actually *running* this, but I have no objections to the code-form as is.

LGTM.

**Comment by josteink** [comment]
@rickbutton : It seems you will have to sign off this PR, if we are to get it merged :smile:

**Comment by system32uwu** [comment]
Any updates on this PR?

**Comment by thiag0mei** [comment]
I would suggest building this yourself from dalyIsaac's fork as rickbutton has been missing for a while. See [/scripts/buildandinstall.ps1](https://github.com/dalyIsaac/workspacer/blob/main/scripts/buildandinstall.ps1)

**Comment by josteink** [comment]
At this point I might just suggest creating a community fork. Just create a Github workspacer-organisation and take it from there. 

And feel free to invite @rickbutton too, if he at some point in the future decides to return from his absence 🙂

**Comment by schiltz3** [comment]
I have no experience creating or maintaining a github org, but I have a couple of PR's I will submit if someone makes a community fork.

**Comment by josteink** [comment]
Fork discussed in this issue: https://github.com/rickbutton/workspacer/issues/211

**Comment by josteink** [comment]
Can anyone else review and approve this PR? It needs one more approval.

**Review by system32uwu — APPROVED** [review]

**Comment by josteink** [comment]
Thanks for the review.

To enable merging it needs to be done by someone with write-access though. 😃

**Pull request merged**
