### PR TITLE
Fixes the ability to restart with a message

### LINKED ISSUE #37: On restart, something went wrong and permanently hid some of my windows :(
I used the tray icon to restart workspacer after a config change.

At this point some of my windows didn't come back, eg, I have two firefox windows and one of them came back and the other one didn't.

I had to restart my computer to fix this.

Two things could be done here:

1. A dedicated `fix-my-windows.exe` util outside of workspacer to show windows that workspacer touched
2. make sure the tray icon "restart" isn't doing something broken and weird

### PR DESCRIPTION
**Pull request by dalyIsaac**
This fixes the following issues related to waking from sleep:

- Missing window handle
- Object disposed
- Display settings changed
- `TextBlockMessage` didn't display buttons

### Missing window handle

When the OS wakes from sleep, sometimes the `BarForm` will try to redraw the window, even though the window handle has not yet been created (presumably it was destroyed as part of going to sleep):
Exception thrown when the window handle has not yet been created

### Object disposed

Sometimes after waking from sleep, `BarForm` has been disposed of.
`System.ObjectDisposedException`

### Display settings changed

Sometimes when the OS wakes from sleep, it thinks that the display settings have changed, which triggers `ConfigContext::HandleDisplaySettingsChanged` https://github.com/rickbutton/workspacer/blob/d9da742fb684eb3db38e770b39c24b46e8c1193e/src/workspacer/ConfigContext.cs#L52 

`HandleDisplaySettingsChanged` sends the action `LauncherAction.RestartWithMessage` to the workspace watcher.
https://github.com/rickbutton/workspacer/blob/d9da742fb684eb3db38e770b39c24b46e8c1193e/src/workspacer/ConfigContext.cs#L223-L233

The workspace watcher should create a `TextBlockMessage`:
https://github.com/rickbutton/workspacer/blob/cd334dca261cba1181783a8e26a9350e97f5aa3a/src/workspacer.Watcher/Program.cs#L58-L62

https://github.com/rickbutton/workspacer/blob/cd334dca261cba1181783a8e26a9350e97f5aa3a/src/workspacer.Watcher/Program.cs#L132-L140

The `TextBlockMessage` is not opened as `HandleDisplaySettingsChanged` calls `CleanupAndExit` immediately after sending `LauncherAction.Restart`. 

`CleanupAndExit` calls `Environment.Exit`, which also kills the workspace watcher.

https://github.com/rickbutton/workspacer/blob/e0e3c0607082926d7dca8c5d41325c057f6017ba/src/workspacer/ConfigContext.cs#L193-L198

Removing `Environment.Exit` does not prevent the watcher from being shutdown when the user wants to quit - that is handled by `LauncherAction.Quit`:

https://github.com/rickbutton/workspacer/blob/e0e3c0607082926d7dca8c5d41325c057f6017ba/src/workspacer/ConfigContext.cs#L169-L178

`Application.Exit` should suffice for stopping all threads in the main workspacer process, according to the [`Application.Exit` documentation](https://docs.microsoft.com/en-US/dotnet/api/system.windows.forms.application.exit?redirectedfrom=MSDN&view=net-5.0#code-try-1:~:text=The%20Exit%20method%20stops%20all%20running,closes%20all%20windows%20of%20the%20application.).

### `TextBlockMessage` didn't display buttons

The buttons for `TextBlockMessage` would only be displayed after going full screen. Updating the dimensions and locations of controls in `TextBlockMessage` resolves this.

## P.S.

This may also fix #37.

### CODE REVIEW

**Comment by josteink** [comment]
This seems like a really well meant and well researched issue, but I really don't have anywhere to test these changes (I don't have a laptop running Windows anywhere).

I'd appreciate it if someone else could test these changes.

Cc: @N1x0 @rickbutton

**Comment by dalyIsaac** [comment]
A quick way to test `HandleDisplaySettingsChanged` is to open the Display page in the Windows Settings app. If you have multiple monitors, you can _slightly_ change a monitor's position and press 
Apply". That triggers `HandleDisplaySettingsChanged`.

p.s. @josteink thanks for reviewing all these PRs even though you don't use Windows anymore 🙏.

**Comment by josteink** [comment]
PRs haven’t been merged in *months* and Rick haven’t been answering emails either. 

Right now it seems a fork is needed to keep workspacer going forwards. 

I’m discussing this in a issue here: https://github.com/rickbutton/workspacer/issues/211. Feel free to let me know your thoughts.

**Review by N1x0 — APPROVED** [review]
LGTM!

**Review by sitiom — APPROVED** [review]
Put a comment on the empty try-catch block. Otherwise, LGTM!

**Pull request merged**
