### PR TITLE
Using UserEnviromentVariables to set the folder Path

### PR DESCRIPTION
**Pull request by dantearaujo1**
Now we can set a UserEnviromentVariable to move .config/workspacer folder.

### CODE REVIEW

**Comment by josteink** [comment]
Change looks pretty harmless to me, and I'm OK with the implementation as is.

But you may want to document it? Try to find somewhere in [the docs](https://github.com/workspacer/workspacer/tree/master/docs) and add it there too? :)

**Comment by dantearaujo1** [comment]
I'll do my best

**Review by josteink — APPROVED** [review]
LGTM

**Comment by josteink** [comment]
Thanks for the patch. Consider it merged!

**Pull request merged**
