### PR TITLE
Previous workspace got wrong index fix

### PR DESCRIPTION
**Pull request by kmpi**
Previous workspace looked at the wrong container, and got the wrong index, changing to the correct container, now gives the correct amount of workspaces, when looking at which index to switch to.

issue #198

### CODE REVIEW

**Review by josteink — APPROVED** [review]
LGTM.

**Review by schiltz3 — APPROVED** [review]
LGTM

**Comment by josteink** [comment]
Can anyone else (with write-access) review and approve this PR? It needs one more approval.

**Review by dalyIsaac — APPROVED** [review]
LGTM!

**Pull request merged**
