### PR TITLE
Add winget installation

### PR DESCRIPTION
**Pull request by sitiom**
Edit: It was actually added to winget way back last year but it came off the top of my head (winget wasn't still stable at that time).

### CODE REVIEW

**Comment by system32uwu** [comment]
Looks like it was uploaded by [rickbutton](https://winget.run/pkg/rickbutton/workspacer), has anyone tried installing through winget? Not sure how it works, but the version there is the latest stable release, isn't there a way to also get versions from other tags? (like beta or unstable). This is fine btw, but since that release is from last year I don't know how many people would want to use this method.

**Review by system32uwu — APPROVED** [review]

**Comment by sitiom** [comment]
> Looks like it was uploaded by [rickbutton](https://winget.run/pkg/rickbutton/workspacer),

Actually, I do remember now. [It was me!](https://github.com/microsoft/winget-pkgs/pull/5731) (Not sure how I forgot that I myself put it there. I use chocolatey most of the time, and there was a package fix just yesterday and I thought it was just recently added 😅)

> has anyone tried installing through winget? Not sure how it works, but the version there is the latest stable release, isn't there a way to also get versions from other tags? (like beta or unstable). This is fine btw, but since that release is from last year I don't know how many people would want to use this method.

Yes, it does work. But support for different release channels is still an ongoing issue (https://github.com/microsoft/winget-cli/issues/147). Would need to wait for that.

**Comment by dalyIsaac** [comment]
Speaking of releases, it'd be great if #233 could be reviewed - once that's done I'll update the beta branch.

**Review by dalyIsaac — APPROVED** [review]

**Comment by sitiom** [comment]
> Speaking of releases, it'd be great if #233 could be reviewed - once that's done I'll update the beta branch.

Also would need to fix this as well https://github.com/workspacer/workspacer/issues/248.

**Pull request merged**
