### PR TITLE
Added a beta release branch

### PR DESCRIPTION
**Pull request by dalyIsaac**
This gives us the ability to have beta releases.

This is based on the `unstable` workflow.

To create a new release:

1. Create `beta` tag on your local branch
2. Push to the remote

The workflow builds workspacer and generates an installer. It deletes the `beta` tag and replaces it with the version number.

The version number is formatted like `v0.9.11-beta.2`. The final number in the versioning relies on the `github.run_number` - this means that it's possible to have `v0.9.11-beta.2` followed by `v0.9.12-beta.3`.

~The beta GitHub action is based on the `unstable.yml` workflow. I'm not entirely sure how to test this locally - hopefully if there's any errors they'll be picked up in review 🤞.~

I've tested the workflow on https://github.com/dalyIsaac/workspacer-actions-test

### CODE REVIEW

**Comment by sitiom** [comment]
There is [act](https://github.com/nektos/act) but I haven't tried this out myself yet. I just usually run the actions on the fork I am working on. Maybe fork the project and run it there to see if it works fine.

**Comment by sitiom** [comment]
There is [act](https://github.com/nektos/act) but I haven't tried this out myself yet. I just usually run the actions on the fork I am working on. Maybe fork the project and run it there to see if it works fine.

**Comment by sitiom** [comment]
There is [act](https://github.com/nektos/act) but I haven't tried this out myself yet. I just usually run the actions on the fork I am working on. Maybe fork the project and run it there to see if it works fine.

**Comment by sitiom** [comment]
There is [act](https://github.com/nektos/act) but I haven't tried this out myself yet. I just usually run the actions on the fork I am working on. Maybe fork the project and run it there to see if it works fine.

**Review by sitiom — APPROVED** [review]
LGTM!

**Review by josteink — APPROVED** [review]

**Pull request merged**
